spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    password: anonim
    username: anonim
    url: jdbc:postgresql://localhost:5432/anonim
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  rabbitmq:
    password: ${RABBIT_MQ_PASSWORD:123}
    username: ${RABBIT_MQ_USERNAME:ahrorjon}
    addresses: ${RABBIT_MQ_ADDRESSES:localhost:5672}
logging:
  file:
    name: logback
server:
  port: 7578